on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 * * * *'

jobs:
  test:
    name: Test
    timeout-minutes: 20
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04,windows-latest, windows-2022, windows-2019,macos-latest, macos-12, macos-11,macos-13]
        version: ['10.x','12.x','15.x','20.x']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout to code
      uses: actions/checkout@v4
    - name: install Node js Version ${{ matrix.version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.version }}
    - name: install package
      run: npm i
    - name: run test
      run: npm test
