name: keeplive

on:  
  schedule:  
    - cron: '0 0 */15 * *'
  workflow_dispatch:  
    inputs:  
      operating_system:
        description: 'Operating System'
        type: choice
        required: true
        default: 'ubuntu-latest'
        options:
          - 'ubuntu-latest'
          - 'windows-latest'
      branch:  
        description: 'branch'  
        required: true  
        default: 'main'
jobs:  
  update-file:  
    runs-on: ubuntu-latest  
    
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4
      - name: Update file  
        run: |  
          echo "This file was updated on $(date)" > f.txt 
      - name: Generate unique identifier  
        id: generate_id  
        run: |  
          echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV  
          uuid=$(uuidgen)  
          echo "UUID=${uuid}" >> $GITHUB_ENV
      - name: Commit changes  
        run: | 
          git config --global user.name "botuser"  
          git config --global user.email "botuser@example.com" # Use your email
          git add f.txt  # Change this to your file path  
          git commit -m "Automated commit: Date=${DATE}, UUID=${UUID}"
          git push origin main   
