name: keeplive

on:  
  push:
    branches:
      - main
  schedule:  
    - cron: '0 0 */15 * *'

jobs:  
  update-file:  
    runs-on: ubuntu-latest  
    
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  

      - name: Update file  
        run: |  
          echo "This file was updated on $(date)" > f.txt 

      - name: Commit changes  
        run: |  
          git config --local user.email "mohamadrezaeimohammad@gmail.com"  
          git config --local user.name "mohamadrezaeimohammad"
          git add f.txt  # Change this to your file path  
          git commit -m "Update file"  
          git push origin main   
          env:  
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
